name: Flutter Analyze

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter pub add intl_utils
      - run: flutter pub run intl_utils:generate
      - run: flutter analyze .
