name: Release

on:
  push:
    tags:
      - '*'

jobs:
  flutter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter pub add intl_utils
      - run: flutter pub run intl_utils:generate
      - run: flutter build windows
      - uses: vimtor/action-zip@v1
        with:
          files: build/windows/runner/Release/ addons/windows/
          recursive: true
          dest: dashboard-windows.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dashboard-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}